site_name: Razmjena
site_description: Razmjena je interaktivna baza podataka znanstvenih grupa koje djeluju na istraživačkim i visokoškolskim ustanovama u Hrvatskoj.
site_author: Vedran Miletić
site_url: https://razmjena.org/
copyright: Autorska prava &copy; <a href="https://gaseri.org/hr/">Grupa za aplikacije i usluge na eksaskalarnoj istraživačkoj infrastrukturi</a> 2022 – 2023. Sva prava pridržana. <a href="#__consent">Promjena postavki kolačića</a>.
repo_url: https://github.com/razmjena/razmjena/
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
  language: hr
  features:
    - content.action.edit
  icon:
    edit: material/pencil
extra:
  analytics:
    provider: google
    property: G-WGBKHXW2YF
  consent:
    title: Cookie consent
    description: Koristimo kolačiće za prepoznavanje vaših ponovnih posjeta, pohranu vaših preferencija i mjerenje učinkovitosti našeg web sjedišta. Svojim pristankom nam pomažete poboljšati naše web sjedište kako bi na njemu budući posjetitelji lakše pronašli ono što žele.
plugins:
  - search
  - social
  - tags:
      tags_file: index.md
